/**
 * Documentation-side RFC coverage map.
 *
 * Keeps docs rendering and reference pages aligned with module ownership,
 * exported symbols, and standards traceability notes.
 */

export interface RfcMapEntry {
    module: string;
    rfc: string;
    sections: string[];
    exports: string[];
    notes: string;
}

export const RFC_MAP: RfcMapEntry[] = [
    {
        module: 'src/structured-fields.ts',
        rfc: 'RFC 8941',
        sections: ['3', '4'],
        exports: [
            'parseSfList',
            'parseSfDict',
            'parseSfItem',
            'serializeSfList',
            'serializeSfDict',
            'serializeSfItem',
            'SfToken',
        ],
        notes: 'Core Structured Field parsing/serialization for list, dictionary, and item values.',
    },
    {
        module: 'src/structured-fields.ts',
        rfc: 'RFC 9651',
        sections: ['3.3.7', '3.3.8', '4.1.10', '4.1.11', '4.2.10'],
        exports: ['SfDate', 'SfDisplayString', 'parseSfItem', 'serializeSfItem'],
        notes: 'Date and Display String support, including lowercase pct-encoding and strict UTF-8 decode.',
    },
    {
        module: 'src/priority.ts',
        rfc: 'RFC 9218',
        sections: ['4', '4.1', '4.2', '5', '8'],
        exports: ['parsePriority', 'formatPriority', 'applyPriorityDefaults', 'mergePriority'],
        notes: 'Priority dictionary handling with strict SF parse, permissive member semantics, defaults, and client/server merge helpers.',
    },
    {
        module: 'src/compression-dictionary.ts',
        rfc: 'RFC 9842',
        sections: ['2', '2.1', '2.2', '2.3', '6.1', '6.2'],
        exports: [
            'parseUseAsDictionary',
            'formatUseAsDictionary',
            'validateUseAsDictionary',
            'parseAvailableDictionary',
            'formatAvailableDictionary',
            'parseDictionaryId',
            'formatDictionaryId',
            'matchesDictionary',
            'selectBestDictionary',
            'mergeDictionaryVary',
        ],
        notes: 'Use-As-Dictionary, Available-Dictionary, and Dictionary-ID parsing/formatting with deterministic dictionary matching/selection and Vary merge helper; dcb/dcz stream codecs remain out of scope.',
    },
    {
        module: 'src/targeted-cache-control.ts',
        rfc: 'RFC 9213',
        sections: ['2', '2.1', '2.2', '3.1'],
        exports: [
            'parseTargetedCacheControl',
            'formatTargetedCacheControl',
            'parseCdnCacheControl',
            'formatCdnCacheControl',
            'selectTargetedCacheControl',
        ],
        notes: 'Targeted cache-control SF dictionary parsing/formatting with CDN-Cache-Control aliases and target-list precedence selection with Cache-Control fallback.',
    },
    {
        module: 'src/cache-groups.ts',
        rfc: 'RFC 9875',
        sections: ['2', '2.1', '2.2.1', '3'],
        exports: [
            'parseCacheGroups',
            'formatCacheGroups',
            'parseCacheGroupInvalidation',
            'formatCacheGroupInvalidation',
            'sharesCacheGroup',
        ],
        notes: 'Cache-Groups and Cache-Group-Invalidation SF list parsing/formatting with parameter-ignore semantics, safe-method invalidation ignore behavior, and same-origin case-sensitive group matching.',
    },
    {
        module: 'src/early-data.ts',
        rfc: 'RFC 8470',
        sections: ['5.1', '5.2'],
        exports: ['parseEarlyData', 'formatEarlyData', 'hasEarlyDataSignal', 'canSend425'],
        notes: 'Early-Data signal parsing/formatting and 425 Too Early eligibility helpers; transport-level anti-replay strategy remains out of scope.',
    },
    {
        module: 'src/early-hints.ts',
        rfc: 'RFC 8297',
        sections: ['2'],
        exports: [
            'EARLY_HINTS_STATUS',
            'parseEarlyHintsLinks',
            'formatEarlyHintsLinks',
            'validateEarlyHintsLinks',
            'extractPreloadLinks',
            'mergeEarlyHintsLinks',
        ],
        notes: 'Early Hints (103) Link helper utilities for tolerant parse, strict format/validation, preload extraction, and deterministic multi-batch merge/dedupe behavior.',
    },
    {
        module: 'src/additional-status.ts',
        rfc: 'RFC 6585',
        sections: ['3', '4', '5', '6'],
        exports: [
            'Rfc6585StatusCode',
            'parseRfc6585StatusCode',
            'formatRfc6585StatusCode',
            'validateRfc6585StatusCode',
            'getRfc6585StatusInfo',
            'formatRfc6585Headers',
        ],
        notes: 'Helpers for 428/429/431/511 parsing/formatting/validation with deterministic no-store response headers and optional Retry-After support for 429.',
    },
    {
        module: 'src/alt-svc.ts',
        rfc: 'RFC 7838',
        sections: ['3', '3.1', '5'],
        exports: ['parseAltSvc', 'formatAltSvc', 'parseAltUsed', 'formatAltUsed'],
        notes: 'Alt-Svc and Alt-Used header-level parsing/formatting with clear-token handling, ordered alternative preservation, tolerant malformed-member skipping, and ma/persist parameter support.',
    },
    {
        module: 'src/patch.ts',
        rfc: 'RFC 5789',
        sections: ['2', '2.2', '3.1', '3.2'],
        exports: ['parseAcceptPatch', 'formatAcceptPatch', 'supportsPatch'],
        notes: 'Accept-Patch parsing/formatting with strict malformed-member rejection and PATCH capability detection.',
    },
    {
        module: 'src/json-patch.ts',
        rfc: 'RFC 6902',
        sections: ['3', '4', '4.1', '4.2', '4.3', '4.4', '4.5', '4.6', '5', '6'],
        exports: [
            'JSON_PATCH_MEDIA_TYPE',
            'parseJsonPatch',
            'tryParseJsonPatch',
            'formatJsonPatch',
            'validateJsonPatch',
            'applyJsonPatch',
        ],
        notes: 'JSON Patch document parsing, semantic validation, and immutable sequential apply helpers with fail-fast operation semantics and RFC 6901 pointer handling.',
    },
    {
        module: 'src/json-merge-patch.ts',
        rfc: 'RFC 7396',
        sections: ['2', '3', '4', 'Appendix A'],
        exports: [
            'MERGE_PATCH_CONTENT_TYPE',
            'parseJsonMergePatch',
            'formatJsonMergePatch',
            'validateJsonMergePatch',
            'applyJsonMergePatch',
        ],
        notes: 'JSON Merge Patch parsing, semantic validation/formatting, and immutable MergePatch apply behavior including object recursion, null-member deletion, and whole-value replacement semantics.',
    },
    {
        module: 'src/json-canonicalization.ts',
        rfc: 'RFC 8785',
        sections: ['3.1', '3.2.1', '3.2.2', '3.2.3', '3.2.4', '5'],
        exports: [
            'formatCanonicalJson',
            'formatCanonicalJsonUtf8',
            'validateCanonicalJson',
            'parseCanonicalJson',
        ],
        notes: 'Canonical JSON serialization and verification helpers with recursive UTF-16 key sorting, ECMAScript primitive serialization, lone-surrogate rejection, and UTF-8 output generation; signature workflows remain out of scope.',
    },
    {
        module: 'src/ni.ts',
        rfc: 'RFC 6920',
        sections: ['2', '3', '3.1', '4', '5', '8.1', '9.4', '9.5'],
        exports: [
            'parseNiUri',
            'formatNiUri',
            'compareNiUris',
            'parseNiUrlSegment',
            'formatNiUrlSegment',
            'toWellKnownNiUrl',
            'fromWellKnownNiUrl',
            'computeNiDigest',
            'verifyNiDigest',
        ],
        notes: 'Named Information URI parsing/formatting, URL segment mapping, .well-known conversion, and SHA-256 digest verification helpers.',
    },
    {
        module: 'src/well-known.ts',
        rfc: 'RFC 8615',
        sections: ['3'],
        exports: [
            'WELL_KNOWN_PREFIX',
            'isWellKnownPath',
            'isWellKnownUri',
            'validateWellKnownSuffix',
            'buildWellKnownPath',
            'buildWellKnownUri',
            'parseWellKnownPath',
        ],
        notes: 'Well-known URI/path helpers enforcing top-level /.well-known/ prefix and single-segment suffix constraints.',
    },
    {
        module: 'src/link-template.ts',
        rfc: 'RFC 9652',
        sections: ['2', '2.1'],
        exports: [
            'parseLinkTemplateHeader',
            'formatLinkTemplateHeader',
            'expandLinkTemplate',
            'resolveTemplateVariableUri',
        ],
        notes: 'Link-Template Structured Field parsing/formatting with URI Template expansion and var-base variable URI resolution.',
    },
    {
        module: 'src/auth/pkce.ts',
        rfc: 'RFC 7636',
        sections: ['4.1', '4.2', '4.3', '4.5', '4.6', '7.1', '7.2', 'Appendix A', 'Appendix B'],
        exports: [
            'generatePkceCodeVerifier',
            'derivePkceCodeChallenge',
            'verifyPkceCodeVerifier',
            'validatePkceCodeVerifier',
            'validatePkceCodeChallenge',
            'parsePkceAuthorizationRequestParams',
            'formatPkceAuthorizationRequestParams',
            'parsePkceTokenRequestParams',
            'formatPkceTokenRequestParams',
        ],
        notes: 'PKCE verifier/challenge generation, derivation, and verification for plain/S256 with strict ABNF validators and tolerant authorization/token request parameter parsers; OAuth flow orchestration and extension methods remain out of scope.',
    },
    {
        module: 'src/auth/dpop.ts',
        rfc: 'RFC 9449',
        sections: ['4.1', '4.2', '4.3', '7.1', '8.1', '8.2', '9'],
        exports: [
            'parseDpopHeader',
            'formatDpopHeader',
            'parseDpopAuthorization',
            'formatDpopAuthorization',
            'parseDpopChallenge',
            'formatDpopChallenge',
            'parseDpopProofJwt',
            'formatDpopProofJwt',
            'validateDpopProofJwt',
            'computeDpopAth',
            'parseDpopNonce',
            'formatDpopNonce',
            'validateDpopNonce',
            'DpopChallenge',
            'DpopError',
            'DpopJwk',
            'DpopProofJwt',
            'DpopProofJwtHeader',
            'DpopProofJwtPayload',
            'DpopProofJwtValidationOptions',
        ],
        notes: 'DPoP proof JWT parse/format/validate helpers with token68 header parsing, access-token hash computation, nonce parsing, and WWW-Authenticate challenge support; JOSE signature verification and key binding enforcement remain out of scope.',
    },
    {
        module: 'src/auth/webauthn.ts',
        rfc: 'W3C WebAuthn Level 3',
        sections: [
            '5.1.8',
            '5.1.9',
            '5.8.1',
            '6.1',
            '6.1.1',
            '7.1',
            '7.2',
            '7.2.8',
            '7.2.10',
            '13.4.3',
            '13.4.9',
        ],
        exports: [
            'parseWebauthnBase64url',
            'formatWebauthnBase64url',
            'validateWebauthnBase64url',
            'parseWebauthnCreationOptionsFromJson',
            'formatWebauthnCreationOptionsToJson',
            'validateWebauthnCreationOptions',
            'parseWebauthnRequestOptionsFromJson',
            'formatWebauthnRequestOptionsToJson',
            'validateWebauthnRequestOptions',
            'parseWebauthnClientDataJson',
            'formatWebauthnClientDataJson',
            'validateWebauthnClientData',
            'parseWebauthnAuthenticatorData',
            'validateWebauthnAuthenticatorData',
            'validateWebauthnCoseAlgorithm',
            'WEBAUTHN_COSE_ALGORITHM_IDS',
        ],
        notes: 'WebAuthn v1 parse/format/validate helpers for strict base64url members, creation/request JSON option codecs, clientDataJSON verification checks with HTTPS-by-default formatting semantics, and authenticatorData structural parsing with flagsByte/flags consistency checks and CBOR map enforcement for credentialPublicKey/extension outputs; attestation statement verification, full CBOR semantic decoding, CTAP orchestration, and related-origins processing remain out of scope. Uses RFC 4648 Section 5 base64url rules and RFC 9053 Section 2 COSE algorithm identifiers for deterministic validation defaults.',
    },
    {
        module: 'src/oauth-authorization-server-metadata.ts',
        rfc: 'RFC 8414',
        sections: ['2', '2.1', '3', '3.1', '3.2', '3.3', '4'],
        exports: [
            'OAUTH_AUTHORIZATION_SERVER_WELL_KNOWN_SUFFIX',
            'parseAuthorizationServerMetadata',
            'parseAuthorizationServerMetadataObject',
            'formatAuthorizationServerMetadata',
            'validateAuthorizationServerMetadata',
            'buildAuthorizationServerMetadataUrl',
            'mergeSignedAuthorizationServerMetadata',
        ],
        notes: 'Authorization server metadata parse/validate/format helpers with RFC 8414 well-known URL derivation, exact issuer comparison options, and signed-claims precedence merge support without JOSE verification.',
    },
    {
        module: 'src/webmention.ts',
        rfc: 'W3C Webmention',
        sections: ['3.1.2', '3.1.3', '3.2.1', '3.2.3', '6'],
        exports: [
            'WEBMENTION_REL',
            'WEBMENTION_CONTENT_TYPE',
            'discoverWebmentionEndpoint',
            'parseWebmentionRequest',
            'validateWebmentionRequest',
            'formatWebmentionRequest',
            'isWebmentionSuccessStatus',
        ],
        notes: 'Webmention endpoint discovery from HTTP Link headers and HTML rel values with deterministic precedence, plus tolerant parser and strict validator/formatter helpers for x-www-form-urlencoded source/target request payloads.',
    },
    {
        module: 'src/trace-context.ts',
        rfc: 'W3C Trace Context',
        sections: ['3.2', '3.3', '3.5', '4.2', '4.3'],
        exports: [
            'parseTraceparent',
            'formatTraceparent',
            'validateTraceparent',
            'parseTracestate',
            'formatTracestate',
            'validateTracestate',
            'updateTraceparentParent',
            'restartTraceparent',
            'addOrUpdateTracestate',
            'removeTracestateKey',
            'truncateTracestate',
        ],
        notes: 'Trace Context traceparent/tracestate parsing, formatting, validation, parent rotation, and tracestate mutation helpers with strict version 00 behavior.',
    },
    {
        module: 'src/fetch-metadata.ts',
        rfc: 'W3C Fetch Metadata',
        sections: ['2.1', '2.2', '2.3', '2.4', '5', '5.1'],
        exports: [
            'parseSecFetchDest',
            'formatSecFetchDest',
            'parseSecFetchMode',
            'formatSecFetchMode',
            'parseSecFetchSite',
            'formatSecFetchSite',
            'parseSecFetchUser',
            'formatSecFetchUser',
            'parseFetchMetadata',
            'evaluateFetchMetadataPolicy',
            'fetchMetadataVary',
        ],
        notes: 'Structured Field parsing/formatting for Sec-Fetch-* headers with forward-compatible unknown-token handling, strict/permissive policy decisions, and Vary merge helper.',
    },
    {
        module: 'src/clear-site-data.ts',
        rfc: 'W3C Clear Site Data',
        sections: ['3.1', '4.1'],
        exports: [
            'parseClearSiteData',
            'formatClearSiteData',
            'validateClearSiteData',
            'ClearSiteDataType',
            'ClearSiteDataDirective',
        ],
        notes: 'Clear-Site-Data quoted-string list parsing/formatting with strict validator behavior, unknown-directive ignore semantics, malformed-list rejection to empty parse results, and wildcard expansion to known data types.',
    },
    {
        module: 'src/referrer-policy.ts',
        rfc: 'W3C Referrer Policy',
        sections: ['3', '4.1', '8.1', '8.2', '11.1'],
        exports: [
            'parseReferrerPolicy',
            'parseReferrerPolicyHeader',
            'formatReferrerPolicy',
            'validateReferrerPolicy',
            'selectEffectiveReferrerPolicy',
            'ReferrerPolicyToken',
            'ReferrerPolicy',
        ],
        notes: 'Referrer-Policy header parsing/formatting helpers with last-recognized-token semantics, unknown-token ignore behavior for forward-compatible fallbacks, syntax-invalid null results, and redirect-style effective-policy selection that only updates on non-empty parsed tokens.',
    },
    {
        module: 'src/reporting.ts',
        rfc: 'W3C Reporting API',
        sections: ['2.2', '2.4', '3.2', '3.3', '3.6', '10.2'],
        exports: [
            'REPORTS_MEDIA_TYPE',
            'parseReportingEndpoints',
            'formatReportingEndpoints',
            'processReportingEndpointsForResponse',
            'stripUrlForReport',
            'serializeReports',
            'formatReportsJson',
            'parseReportsJson',
            'ReportingEndpoint',
            'ReportingReport',
            'ReportingSerializedReport',
        ],
        notes: 'Reporting-Endpoints Structured Field dictionary parsing/formatting with URI-reference validation, response-relative endpoint resolution, potentially trustworthy origin filtering, URL stripping for report payloads, and application/reports+json serialization/parsing helpers with attempts-counter increment semantics.',
    },
    {
        module: 'src/csp.ts',
        rfc: 'W3C CSP3',
        sections: ['2.2.1', '2.2.2', '2.3.1', '3.1', '3.2', '6.4.2', '6.5'],
        exports: [
            'parseContentSecurityPolicy',
            'formatContentSecurityPolicy',
            'parseContentSecurityPolicyReportOnly',
            'formatContentSecurityPolicyReportOnly',
            'parseContentSecurityPolicies',
            'validateContentSecurityPolicy',
            'parseCspSourceList',
            'formatCspSourceList',
            'validateCspSourceList',
            'ContentSecurityPolicy',
            'CspDirectiveName',
            'CspSourceKeyword',
            'CspHashAlgorithm',
            'CspSourceExpression',
        ],
        notes: 'Subset parser/formatter/validator for Content-Security-Policy and Content-Security-Policy-Report-Only header values covering selected CSP1-era directives, source-expression parsing (keyword/nonce/hash/scheme/host), unknown-directive ignore behavior, and strict semantic validation for serialization.',
    },
    {
        module: 'src/openapi.ts',
        rfc: 'OpenAPI 3.1.1',
        sections: [
            '3.2.1',
            '4.8.12',
            '4.8.13',
            '4.8.15',
            '4.8.18',
            '4.8.19',
            '4.8.23',
            '4.8.30',
            'Runtime Expressions',
            'Appendix C',
        ],
        exports: [
            'normalizeOpenApiParameterSpec',
            'formatQueryParameter',
            'parseQueryParameter',
            'formatPathParameter',
            'parsePathParameter',
            'formatHeaderParameter',
            'parseHeaderParameter',
            'formatCookieParameter',
            'parseCookieParameter',
            'parseOpenApiRuntimeExpression',
            'formatOpenApiRuntimeExpression',
            'isOpenApiRuntimeExpression',
            'evaluateOpenApiRuntimeExpression',
            'materializeOpenApiLinkValues',
            'resolveOpenApiCallbackUrl',
            'parseOpenApiSecurityRequirements',
            'tryParseOpenApiSecurityRequirements',
            'validateOpenApiSecurityRequirements',
            'normalizeOpenApiSecurityRequirements',
            'resolveEffectiveOpenApiSecurity',
            'evaluateOpenApiSecurity',
            'compileOpenApiPathMatcher',
            'extractOpenApiPathParams',
            'listOpenApiServerCandidates',
            'resolveOpenApiServerUrl',
            'lintOpenApiDocument',
        ],
        notes: 'OpenAPI 3.1.1 utilities for parameter serialization styles, runtime-expression evaluation, link/callback materialization, security requirement normalization/evaluation, path matching/server URL resolution, and structural lint checks for common spec pitfalls.',
    },
];
