export interface RfcMapEntry {
    module: string;
    rfc: string;
    sections: string[];
    exports: string[];
    notes: string;
}

export const RFC_MAP: RfcMapEntry[] = [
    {
        module: 'src/structured-fields.ts',
        rfc: 'RFC 8941',
        sections: ['3', '4'],
        exports: [
            'parseSfList',
            'parseSfDict',
            'parseSfItem',
            'serializeSfList',
            'serializeSfDict',
            'serializeSfItem',
            'SfToken',
        ],
        notes: 'Core Structured Field parsing/serialization for list, dictionary, and item values.',
    },
    {
        module: 'src/structured-fields.ts',
        rfc: 'RFC 9651',
        sections: ['3.3.7', '3.3.8', '4.1.10', '4.1.11', '4.2.10'],
        exports: ['SfDate', 'SfDisplayString', 'parseSfItem', 'serializeSfItem'],
        notes: 'Date and Display String support, including lowercase pct-encoding and strict UTF-8 decode.',
    },
    {
        module: 'src/priority.ts',
        rfc: 'RFC 9218',
        sections: ['4', '4.1', '4.2', '5', '8'],
        exports: ['parsePriority', 'formatPriority', 'applyPriorityDefaults', 'mergePriority'],
        notes: 'Priority dictionary handling with strict SF parse, permissive member semantics, defaults, and client/server merge helpers.',
    },
    {
        module: 'src/compression-dictionary.ts',
        rfc: 'RFC 9842',
        sections: ['2', '2.1', '2.2', '2.3', '6.1', '6.2'],
        exports: [
            'parseUseAsDictionary',
            'formatUseAsDictionary',
            'validateUseAsDictionary',
            'parseAvailableDictionary',
            'formatAvailableDictionary',
            'parseDictionaryId',
            'formatDictionaryId',
            'matchesDictionary',
            'selectBestDictionary',
            'mergeDictionaryVary',
        ],
        notes: 'Use-As-Dictionary, Available-Dictionary, and Dictionary-ID parsing/formatting with deterministic dictionary matching/selection and Vary merge helper; dcb/dcz stream codecs remain out of scope.',
    },
    {
        module: 'src/targeted-cache-control.ts',
        rfc: 'RFC 9213',
        sections: ['2', '2.1', '2.2', '3.1'],
        exports: [
            'parseTargetedCacheControl',
            'formatTargetedCacheControl',
            'parseCdnCacheControl',
            'formatCdnCacheControl',
            'selectTargetedCacheControl',
        ],
        notes: 'Targeted cache-control SF dictionary parsing/formatting with CDN-Cache-Control aliases and target-list precedence selection with Cache-Control fallback.',
    },
    {
        module: 'src/cache-groups.ts',
        rfc: 'RFC 9875',
        sections: ['2', '2.1', '2.2.1', '3'],
        exports: [
            'parseCacheGroups',
            'formatCacheGroups',
            'parseCacheGroupInvalidation',
            'formatCacheGroupInvalidation',
            'sharesCacheGroup',
        ],
        notes: 'Cache-Groups and Cache-Group-Invalidation SF list parsing/formatting with parameter-ignore semantics, safe-method invalidation ignore behavior, and same-origin case-sensitive group matching.',
    },
    {
        module: 'src/early-data.ts',
        rfc: 'RFC 8470',
        sections: ['5.1', '5.2'],
        exports: ['parseEarlyData', 'formatEarlyData', 'hasEarlyDataSignal', 'canSend425'],
        notes: 'Early-Data signal parsing/formatting and 425 Too Early eligibility helpers; transport-level anti-replay strategy remains out of scope.',
    },
    {
        module: 'src/alt-svc.ts',
        rfc: 'RFC 7838',
        sections: ['3', '3.1', '5'],
        exports: ['parseAltSvc', 'formatAltSvc', 'parseAltUsed', 'formatAltUsed'],
        notes: 'Alt-Svc and Alt-Used header-level parsing/formatting with clear-token handling, ordered alternative preservation, tolerant malformed-member skipping, and ma/persist parameter support.',
    },
    {
        module: 'src/patch.ts',
        rfc: 'RFC 5789',
        sections: ['2', '2.2', '3.1', '3.2'],
        exports: ['parseAcceptPatch', 'formatAcceptPatch', 'supportsPatch'],
        notes: 'Accept-Patch parsing/formatting with strict malformed-member rejection and PATCH capability detection.',
    },
    {
        module: 'src/ni.ts',
        rfc: 'RFC 6920',
        sections: ['2', '3', '3.1', '4', '5', '8.1', '9.4', '9.5'],
        exports: [
            'parseNiUri',
            'formatNiUri',
            'compareNiUris',
            'parseNiUrlSegment',
            'formatNiUrlSegment',
            'toWellKnownNiUrl',
            'fromWellKnownNiUrl',
            'computeNiDigest',
            'verifyNiDigest',
        ],
        notes: 'Named Information URI parsing/formatting, URL segment mapping, .well-known conversion, and SHA-256 digest verification helpers.',
    },
    {
        module: 'src/well-known.ts',
        rfc: 'RFC 8615',
        sections: ['3'],
        exports: [
            'WELL_KNOWN_PREFIX',
            'isWellKnownPath',
            'isWellKnownUri',
            'validateWellKnownSuffix',
            'buildWellKnownPath',
            'buildWellKnownUri',
            'parseWellKnownPath',
        ],
        notes: 'Well-known URI/path helpers enforcing top-level /.well-known/ prefix and single-segment suffix constraints.',
    },
    {
        module: 'src/link-template.ts',
        rfc: 'RFC 9652',
        sections: ['2', '2.1'],
        exports: [
            'parseLinkTemplateHeader',
            'formatLinkTemplateHeader',
            'expandLinkTemplate',
            'resolveTemplateVariableUri',
        ],
        notes: 'Link-Template Structured Field parsing/formatting with URI Template expansion and var-base variable URI resolution.',
    },
    {
        module: 'src/trace-context.ts',
        rfc: 'W3C Trace Context',
        sections: ['3.2', '3.3', '3.5', '4.2', '4.3'],
        exports: [
            'parseTraceparent',
            'formatTraceparent',
            'validateTraceparent',
            'parseTracestate',
            'formatTracestate',
            'validateTracestate',
            'updateTraceparentParent',
            'restartTraceparent',
            'addOrUpdateTracestate',
            'removeTracestateKey',
            'truncateTracestate',
        ],
        notes: 'Trace Context traceparent/tracestate parsing, formatting, validation, parent rotation, and tracestate mutation helpers with strict version 00 behavior.',
    },
    {
        module: 'src/fetch-metadata.ts',
        rfc: 'W3C Fetch Metadata',
        sections: ['2.1', '2.2', '2.3', '2.4', '5', '5.1'],
        exports: [
            'parseSecFetchDest',
            'formatSecFetchDest',
            'parseSecFetchMode',
            'formatSecFetchMode',
            'parseSecFetchSite',
            'formatSecFetchSite',
            'parseSecFetchUser',
            'formatSecFetchUser',
            'parseFetchMetadata',
            'evaluateFetchMetadataPolicy',
            'fetchMetadataVary',
        ],
        notes: 'Structured Field parsing/formatting for Sec-Fetch-* headers with forward-compatible unknown-token handling, strict/permissive policy decisions, and Vary merge helper.',
    },
];
